services:
  odoo:
    image:
      odoo:16
    build:
      context: .
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
      - DATABASE=odoo
    ports:
      - "8069:8069"
    depends_on:
      - db
  db:
    image:
      postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
volumes:
  db_volume:
